/*
SQLyog Community Edition- MySQL GUI
Host - 5.5.16 
*********************************************************************
Server version : 5.5.16
*/
CREATE TABLE `m_courier_info` (
  `courier_id` int(11) NOT NULL AUTO_INCREMENT,
  `courier_name` varchar(255) DEFAULT NULL,
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `locality` varchar(200) DEFAULT NULL,
  `landmark` varchar(200) DEFAULT NULL,
  `postcode` varchar(10) DEFAULT NULL,
  `city_id` int(11) DEFAULT '0',
  `city_name` varchar(150) DEFAULT NULL,
  `state_name` varchar(150) DEFAULT NULL,
  `country` varchar(150) DEFAULT NULL,
  `ledger_id` int(11) DEFAULT '0',
  `credit_limit_amount` double DEFAULT '0',
  `credit_days` int(11) DEFAULT '0',
  `credit_cycle` int(11) DEFAULT '0',
  `require_payment_advance` tinyint(1) DEFAULT '0',
  `cod_available` tinyint(1) DEFAULT '0',
  `mode_air_courier` tinyint(1) DEFAULT '0',
  `mode_air_cargo` tinyint(1) DEFAULT '0',
  `mode_surface` tinyint(1) DEFAULT '0',
  `mode_rail` tinyint(1) DEFAULT '0',
  `tin_no` varchar(100) DEFAULT NULL,
  `cst_no` varchar(100) DEFAULT NULL,
  `pan_no` varchar(100) DEFAULT NULL,
  `vat_no` varchar(100) DEFAULT NULL,
  `service_tax_no` varchar(100) DEFAULT NULL,
  `shipment_update_template_id` int(11) DEFAULT '0',
  `pincode_list_template_id` int(11) DEFAULT '0',
  `payment_terms_msg` varchar(255) DEFAULT NULL,
  `agreement_copy` varchar(200) DEFAULT NULL,
  `remarks` varchar(2000) DEFAULT NULL,
  `ref_partner_id` int(11) DEFAULT '0',
  `is_active` int(1) DEFAULT '0',
  `created_by` int(11) DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  PRIMARY KEY (`courier_id`)
);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('1','DTDC',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('2','Aramex',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('3','Bluedart',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('4','Speedpost',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('5','First Flight',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('6','Overnight',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('7','Trackon',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('8','Hand Delivery',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('9','Others',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('10','Aramex - Naaptol',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('11','Bluedart - Naaptol',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('12','First Flight - Naaptol',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('13','IndiaOnTime',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('14','Overnite',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('15','',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('16','Flipkart',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('17','SR International',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('18','Durgambha',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
insert into `m_courier_info` (`courier_id`, `courier_name`, `address_line1`, `address_line2`, `locality`, `landmark`, `postcode`, `city_id`, `city_name`, `state_name`, `country`, `ledger_id`, `credit_limit_amount`, `credit_days`, `credit_cycle`, `require_payment_advance`, `cod_available`, `mode_air_courier`, `mode_air_cargo`, `mode_surface`, `mode_rail`, `tin_no`, `cst_no`, `pan_no`, `vat_no`, `service_tax_no`, `shipment_update_template_id`, `pincode_list_template_id`, `payment_terms_msg`, `agreement_copy`, `remarks`, `is_active`, `created_by`, `modified_by`, `created_on`, `modified_on`) values('19','Poornima Travels',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,'0','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);

#alter table `m_courier_info` add column `ref_partner_id` int (11) DEFAULT '0' NULL  after `remarks`;