<div class="container">


<div align="left" style="padding:10px 20px;font-size:110%;" class="pages_heading">

<h1>Terms &amp; Conditions</h1>
<p>
The Terms and Conditions contained herein along form an Agreement regulating our relationship with regard to the use of SnapItToday.com by you.<br>
<p>Please read this Agreement carefully. You are advised to regularly check for any amendments or updates to the terms and conditions from time to time. SnapItToday.com may add to or change or update these Terms of Use, from time to time entirely at its own discretion. You are responsible for checking these Terms of Use periodically to remain in compliance with these terms. Your use of a Site after any amendment to the Terms of Use shall constitute your acceptance of these terms and you also agree to be bound by any such changes/revisions.<br>
<p>Any clause of terms and conditions if deemed invalid, void or for any reason unenforceable, shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the terms and conditions.
</p>

<h2>Definitions:</h2>
<p> 
"Agreement" means the Terms and Conditions (T&C) contained herein under the SnapItToday.com brand name. It will also include references to this Agreement as and when amended, notated, supplemented, varied or replaced.<br>
<p>"Affiliate" being a corporate entity, means any entity, which controls, is controlled by, or is under the common control of the Company and being an individual, means any entity, which is controlled by the Company.<br>
<p>"User/You" means and includes any Customer / Buyer / You (the person or any legal entity) who accept the offer for sale by SnapItToday.com by placing its order on this Site.<br>
<p>"Product's connotes the goods, services promoted / displayed on the Site and offered for any use / sale.
</p>

<h2>Online Purchases</h2>
<p>
This Website is only a venue where Users may meet and interact with us for their sale and purchase transactions. The commercial / contractual terms include without limitation price, shipping costs, date, period, mode of delivery, warranties related to products and services including after sales services related to products and services, etc., over which the we have complete control and the same may be subject to change.<br><br>
<p>The agreement between you and SnapItToday.com is subject to the following terms and conditions :-<br>
<ol>
<li>The User certifies that he/she is at least 18 (eighteen) years of age or has the consent of a parent or legal guardian.</li>
<li>These terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the Shopping services of SnapItToday.com you agree to be bound by the Terms and Conditions.<br>
<li>All prices, unless indicated otherwise are in Indian Rupees.<br>
<li>By indicating User's acceptance to purchase any product or service offered on the site, user is obligated to complete such transactions. Users shall prohibit from indicating its acceptance to purchase products and services where it does not intend to complete such transactions.<br>
<li>Any order placed for a product that is listed at an incorrect price may be cancelled. This shall be regardless of whether the order has been confirmed and/or payment levied. In the event the payment has been processed, the same shall be credited to your account and duly notified to you by email.<br>
<li>In a credit card transaction, you must use your own credit card. SnapItToday.com will not be liable for any credit card fraud. The liability to use a card fraudulently will be on the user and the onus to 'prove otherwise' shall be exclusively on the user.<br>
<li>In the event that a non-delivery occurs on account of a mistake by you (i.e. wrong name or address) any extra cost towards re-delivery shall be claimed from the User placing the order.<br>
<li>Payment gateway takes 24-48 hours to confirm the payment to check for fraudulent transactions. Shipment/delivery time of order processing starts from the day of receipt of the payment confirmed against the order placed with SnapItToday.com. Usually all orders are processed and shipped within 7 working days, once payment is confirmed. However, certain categories of products have different lead-times for delivery due to the nature of the product. Do check the delivery timelines for each product while ordering. SnapItToday.com shall not be liable for any delay / non-delivery of purchased goods in the event of flood, fire, wars, acts of God or any cause that is beyond the control of SnapItToday.com.<br>
<li>The Products shall be subject to manufacturer's terms and conditions for warranty, service and maintenance, and Company does not accept any responsibility for the same. The Company also does not accept any responsibility for the usage of the Products by the User.<br>
<li>SnapItToday shall have no liability for the defects in product received by the customer and the customer consents to agree to the terms of the return policy of the respective supplier in case of any defective products sold by such supplier to the customer.<br>
<li>The User agrees to use the services provided by SnapItToday.com, its affiliates, consultants and contracted companies, for lawful purposes only. Company may assign any or all of its rights under these Terms to its Affiliates without consent of the User.<br>
<li>Any attempt by a User to deliberately damage the Site or undermine the legitimate operation of the Site is in violation of Criminal and Civil Laws and should such an attempt be made, Company reserves the right to seek damages/injunction from any such User to the fullest extent permitted by law.<br>
<li>The User agrees to provide authentic and true information. SnapItToday.com reserves the right to confirm and validate the information and other details provided by the User at any point of time. If upon confirmation such User details are found not to be true (wholly or partly), SnapItToday.com has the right in its sole discretion to reject the registration and debar the User from using the Services available at this website, and / or other affiliated websites without prior intimation whatsoever.<br>
<li>Partial delivery of product needs to be reported within 10 days of receipt of the product.<br>
<li>In the event of non-delivery of the products to the customers, SnapItToday's liability shall be limited only to the refund of the exact amount paid by the customer for the purchase of the product.<br>
<li>SnapItToday's liability to any claims will only be up to and limited to the cost of the product units in question.<br>
<li>Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being canceled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, the said amount will be reversed back in your Card Account.<br>
<li>In case we receive a cancellation notice and the order has not been processed/approved by us, we shall cancel the order and refund the entire amount. We will not be able to cancel orders that have already been processed and shipped out by us. We have the full right to decide whether an order has been processed or not. The customer agrees not to dispute the decision made by us and accept our decision regarding the cancellation.<br>
<li>This User Agreement shall be construed in accordance with the applicable laws of India. The Courts at Delhi shall have exclusive jurisdiction in any proceedings arising out of this agreement. Any dispute or difference either in interpretation or otherwise, of any terms of this User Agreement between the parties hereto, the same shall be referred to an independent arbitrator who will be appointed by SnapItToday, and his decision shall be final and binding on the parties hereto. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time. The arbitration shall be held in Delhi. The High Court of judicature at Delhi alone shall have the jurisdiction and the Laws of India shall apply<br>
<li>SnapItToday.com expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Site. Access to this Site does not confer and shall not be considered as conferring upon anyone any license under any of SnapItToday.com or any third party's intellectual property rights. All rights, including copyright, in this website are owned by or licensed to SnapItToday.com. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of SnapItToday.com. You may not modify, distribute or re-post anything on this website for any purpose.<br>
<li>The SnapItToday.com names and logos and all related product and service names, design marks and slogans are the trademarks or service marks of SnapItToday. All other marks are the property of their respective companies. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.<br>
<li>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Site (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Site for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Site or any related software. All software used on this Site is the property of SnapItToday.com and protected by Indian and international copyright laws. The Contents and software on this Site may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Site is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by SnapItToday.com.<br>
<li>You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that to the fullest extent permitted under applicable law, SnapItToday.com shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable to you.<br>
<li>You agree to defend, indemnify and hold harmless SnapItToday.com, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to SnapItToday.com but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.<br>
<li>The users have read and agree to the SnapItToday.com terms and conditions and also agree to receive promotional e-mailers and SMSs.<br>
<li>This User Agreement is effective unless and until terminated by either you or SnapItToday.com. You may terminate this User Agreement at any time, provided that you discontinue any further use of this Site. SnapItToday.com may terminate this User Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site, Such termination will be without any liability to SnapItToday.com. Upon any termination of the User Agreement by either you or SnapItToday.com, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the User Agreement or otherwise.<br>
<li>All the information regarding the products listed is taken from the company's website & company's catalogue. Some specifications are subject to change without prior notice.<br>
<li><h4>Offers, Coupons & Promotions</h4>
All Offers, Coupons & Promotions are provided to user on Fair use basis & are applicable for 1(one) time purchase only, unless explicitly specified otherwise,<br>
User is eligible to purchase only 1(one) qty of each product which is under offer, unless explicitly specified otherwise & snapittoday.com reserves the right to cancel orders which are not complying the terms,<br>
All Offers, Coupons & Promotions are applicable for consumer only, snapittoday.com reserves the right to cancel whole or part of the any reseller order.<br>
Any Coupons issued to personal use are for their own order only & Snapittoday.com reserves the right to cancel any orders placed by any other user using this coupon.<br>
All Cash Backs unless otherwise specified are issued in the form of SnapCoupons which needs to be redeemed at the time of next orders.<br>
All SnapCoupons should be used before their Validity expires & validity cannot be extended under any circumstances.<br>
All SnapCoupons are valid only if user orders minimum order value unless specified otherwise.<br>
The Cash Back Offers are offered for limited period only & Snapittoday.com reserves the right to extend, alter, discontinue or cancel the offer at any point of time without giving any reason.<br>
SnapCoupons are not valid for Products selected in favorite 5, weekly savings & Snapittoday.com reserves the right to cancel any orders which doesn't comply.<br>
Cash Back Offer is not applicable for orders placed with SnapCoupons.<br>
Incase orders which contain SnapCoupons are cancelled, the proportionate discount amount is subtracted & remaining amount is refunded.<br>
Free Samples given are subject to availability & SnapItToday.com reserves the right to either replace or cancel the free sample.<br>
Only one coupon code per user is applicable.<br>
Snapittoday has the right to cancel any order if any of the terms of service have been violated.<br>

<li><h4>Cash On Delivery (COD):</h4>
SnapItToday's Cash On Delivery service enables buyers to pay for their goods worth Rs. 50,000 on receiving the consignment. For orders more than Rs.50,000, the buyers need to make an upfront payment of 10% and the remaining amount, on receiving the goods.<br>
In case of cancellations after the goods are delivered, SnapItToday.com will accept the consignment only if it is not opened or tampered with and would refund the token amount (if paid). SnapItToday.com will not be liable to take back the goods if the package is unwrapped or meddled with.<br>
If by due diligence, we find that a user is misusing the COD service, we might disable the user's id or charge a processing fee.<br>
The user agrees to receive unlimited messages with regards to their transaction from SnapItToday.com. This clause shall survive till the expiry or termination of this User Agreement.<br>
<li><h4>Know More Link:</h4>
SnapItToday.com may not be able to offer the Cash on Delivery (COD) payment service for a few products.<br>
<li><h4>Residents of following states must provide below mentioned forms and courier them to the following address prior to processing of order:</h4> 
a. Uttar Pradesh: Form 32 needs to be provided by the customer for any purchases above Rs.1000<br>
b. West Bengal: Form 42 needs to be provided by the customer for any purchases above Rs.1000<br>
c. Octroi Wherever applicable will be paid by customer<br>
</ul>
</div>

</div>
